version: "3.9"
services:
  roulette-api:
    container_name: roulette-api
    image: roulette-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - roudb
    environment:
      - DB_URL=postgresql://postgres:admin@roudb:5432/roulettedb

  roudb:
    container_name: roudb
    image: postgres:12
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: roulettedb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}